theme: jekyll-theme-slate
title: Mi CV
#description: CV formato PDF (actualizado a enero de 2024) en este [link](https://github.com/adrianruiz1306/adrianruiz1306.github.io/raw/12d4c82a5d8ec6ec4f506ac60f9dae0800be6d34/cv_adrian_ruiz.pdf).
